variable "vpc_id" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "ecr_repo_name" {}
variable "task_definition_name" {}
variable "containername" {}
variable "container_port" {}
variable "host_port" {}
variable "loadbalancer_sg" {}
variable "ECS_sg" {}
variable "td_cpu" {}
variable "td_memory" {}
variable "container_memory" {}
variable "container_cpu" {}
variable "target_group_name" {}
variable "load_balancer_name" {}
variable "ecs_cluster_name" {}
variable "ecs_service_name" {}
